In [1]:
# numpy Array 

import numpy as np

In [ ]:
# array(): numpy function 

'''
array(data[iterative|sequential], dtype=object, ndmin=0)

'''

In [3]:
# How to create a numpy ndarray 
arr = np.array([2, 4, 5, 3, 5, 7])
print(arr)

[2 4 5 3 5 7]


In [8]:
mat = arr.reshape(2, 3)
print(mat)

[[2 4 5]
 [3 5 7]]


In [ ]:
arr.shape = 2, 3  # by Attribute shape (Read/Write)

[[2 4 5]
 [3 5 7]]


In [30]:
# arange(start, stop, step)
# data = range(1, 10, 10//2)
# print(list(data))

data = np.arange(1, 9, .5)
print(data, type(data))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5] <class 'numpy.ndarray'>


In [28]:
# linspace
data = np.linspace(1, 5, 100)
print(data)

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

In [42]:
# matrix in Numpy 
M1 = [[2, 4, 5], [30, 10, 4], [0, 4, -3]]
M2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Amat1 = np.array(M1)
Amat2 = np.array(M2)

if Amat1.shape == Amat2.shape:
    res = np.add(Amat1, Amat2)
    print('M1')
    print(Amat1)
    print('\nM2')
    print(Amat2)
    print('\nResult: Addition')
    print(res)
else:
    print('Invalid Dimension for the Addition')


M1
[[ 2  4  5]
 [30 10  4]
 [ 0  4 -3]]

M2
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result: Addition
[[ 3  6  8]
 [34 15 10]
 [ 7 12  6]]


In [44]:
mat = np.zeros((3, 5))
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
mat = np.ones((4, 5))
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# arr = np.array([100, 3, 5, 6])
# print(arr)

[100   3   5   6]
