In [48]:
# matrix 
class array:
    def __init__(self, lst):
        self.lst = lst
        
    def __str__(self):
        st = str(self.lst).replace(',', '')
        return st
    def __add__(self, other):
        adder = []
        if len(self.lst) == len(other.lst):
            for i in range(len(self.lst)):
                adder.append(self.lst[i]+other.lst[i])
            return array(adder)
        else:
            return "Length is not same"
    def reshape(self, m, n):
        M = []
        tmp = []
        for i in self.lst:
            tmp.append(i)
            if len(tmp) == n:
                M.append(tmp)
                tmp = []
        return array(M)

arr1 = array([2, 4, 6, 1, 6, 2])
arr2 = array([4, 7, 9, 0, 2, 0])
out = arr1.reshape(3, 2)
print(out)



[[2 4] [6 1] [6 2]]


In [11]:
import numpy as np
import time 
data = range(100000)
arr1 = np.array(data)
lst1 = list(data)

In [42]:
arr1 = np.array([10, 4, 6])
arr2 = np.array([2, 5])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [28]:
strt = time.time()
list_data = [i*2 for i in lst1]
stop = time.time()
print('List time', stop-strt)

strt = time.time()
arr_data = arr1 * 2
stop = time.time()
print('array time', stop-strt)

List time 0.003103017807006836
array time 0.0006363391876220703


In [8]:
import numpy as np


ls = [1, 300, 5, 2, 8, 0]
arr = np.array(ls)
print(arr, type(arr))
print(isinstance(ls, np.ndarray))

[  1 300   5   2   8   0] <class 'numpy.ndarray'>
False


In [ ]:
# Numpy Array 

'''
ndArray = np.array(data[sequential|Iterative], dtype=object, ndmin=0)
'''

In [5]:
import numpy as np
data = range(1, 10)
arr = np.array(data, dtype=complex)
print(arr.ndim)

1


In [12]:
lst = [1, 2, 3, 4, 5]
arr2 = np.array(lst, ndmin=2)
print(arr2)
print('Dimension', arr2.ndim)
print('Shape', arr2.shape)

[[1 2 3 4 5]]
Dimension 2
Shape (1, 5)


In [20]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(lst, dtype='int8')
print(arr)
print(type(arr[0]))
arr.shape = 9, 1
print('last\n',arr)


[1 2 3 4 5 6 7 8 9]
<class 'numpy.int8'>
last
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [30]:
# arange(start, stop, step)
data = np.arange(1, 10, .5)
print(list(data))

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]


In [37]:
# linspace(start, stop, number of sample)
data = np.linspace(0, 1, 10000)
print(data)

[0.00000000e+00 1.00010001e-04 2.00020002e-04 ... 9.99799980e-01
 9.99899990e-01 1.00000000e+00]


In [36]:
data = np.array([1, 200000, 4])
print(data)

[     1 200000      4]


In [49]:
arr = np.array([2.5, 3.5455, 5.7888])

print(np.around(arr, 1))
print(np.sin(arr))

[2.5 3.5 5.8]
[ 0.59847214 -0.39301426 -0.47449065]


In [50]:
# matrix
M1 = [[1, 2, 3], [3, 4, 6]]
M2 = [[0, 3, 4], [1, 9, 6]]

arr1 = np.array(M1)
arr2 = np.array(M2)

if arr1.shape == arr2.shape:
    res = np.add(arr1, arr2)
    print('\nMatrix1')
    print(arr1)
    print('\nMatrix2')
    print(arr2)
    print('\nAddition')
    print(res)
else:
    print('Not valid Dimensions for the Addition')




Matrix1
[[1 2 3]
 [3 4 6]]

Matrix2
[[0 3 4]
 [1 9 6]]

Addition
[[ 1  5  7]
 [ 4 13 12]]
